  services:

    web:
      build:
        context: .\app
        dockerfile: Dockerfile.dev
      command: gunicorn hr_django.wsgi:application --bind 0.0.0.0:8000 --timeout 120
      volumes:
        - static_volume:/home/app/web/staticfiles
        - media_volume:/home/app/web/mediafiles
        - ./app:/home/app/web
      expose:
        - 8000
      env_file:
        - .\.env
      depends_on:
        - db

    db:
      build:
        context: .\db
        dockerfile: Dockerfile
      volumes:
        - postgres_data:/var/lib/postgresql/data
      env_file:
        - .\.env.dev
      environment:
        - POSTGRES_USER=hr
        - POSTGRES_PASSWORD=hr
        - POSTGRES_DB=hr_dev

    nginx:
      build: ./nginx
      volumes:
        - static_volume:/home/app/web/staticfiles
        - media_volume:/home/app/web/mediafiles
      ports:
        - 1337:80
      depends_on:
        - web

  volumes:
    postgres_data:
    static_volume:
    media_volume:
